# Stage 1.
FROM golang:1.25-alpine AS builder

WORKDIR /apps

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    go build -o /nectlife ./cmd/nectlife/

# Stage 2.
FROM alpine:latest AS final

COPY --from=builder /nectlife /bin/nectlife

RUN chmod +x /bin/nectlife

EXPOSE 8080

CMD [ "/bin/nectlife" ]
