-- Step 1: Drop the existing primary key constraint.
-- Note: PostgreSQL often names the primary key constraint "table_name_pkey".
-- You can verify the name with \d session in psql.
ALTER TABLE "session"
DROP CONSTRAINT "session_pkey";

-- Step 2: Add the new 'id' column as the new primary key.
ALTER TABLE "session"
ADD COLUMN "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Step 3: Ensure the 'token' column remains unique and not null.
-- The PRIMARY KEY constraint already provided these, so we add them back.
ALTER TABLE "session"
ALTER COLUMN "token" SET NOT NULL;

ALTER TABLE "session"
ADD CONSTRAINT "session_token_key" UNIQUE ("token");
